theme: jekyll-theme-slate
title: PUBG Placement Prediction - Kaggle Competition
description: A project completed for EE460J Data Science Lab at the University of Texas at Austin by Clive Unger, Benson Huang, Ashwin Gupta, Andy Chang, Avishka Suduwa Dewage
